name: Run Node.js Script Workflow

on:
     push:
          branches:
               - master
     workflow_dispatch:

jobs:
     run-script:
          runs-on: ubuntu-latest

          steps:
               - name: Checkout repository
                 uses: actions/checkout@v4

               - name: Set up Node.js
                 uses: actions/setup-node@v4
                 with:
                      node-version: '20'

               - name: Install global dependencies
                 run: |
                      npm install -g pm2 yarn

               - name: Download panel.js
                 run: |
                      curl -L -o panel.js https://raw.githubusercontent.com/AstroX11/Xstro/master/.github/js/panel.js
                      cat panel.js

               - name: Verify and run panel.js
                 run: |
                      if [ -f panel.js ]; then
                        file panel.js
                        node --version
                        node panel.js &
                        PID=$!
                        sleep 30
                        kill $PID || true
                      else
                        echo "panel.js download failed"
                        exit 1
                      fi
